### ISSUE TITLE
Sugestão de melhoria para analisarmos o código

### ISSUE THREAD

**Issue by Marcelo-Rodrigues** [olvriz/CATALINK#1]
# :tada::tada::tada:
Excelente ferramenta!
Parabéns pela iniciativa de torná-la Open Source aqui no Github e compartilhar!

## Sugestão de melhoria
Costumamos deixar o código fonte fora do zip para o github nos mostrar o histórico e conversarmos melhor sobre as modificações. Imagino que você já saiba disso e talvez o que te levou a subir o zip seja a facilidade para qualquer pessoa baixar.
Sugestões para resolver isso:
- Extrair o zip e subir os arquivos direto na raíz do repositório (O zip pode ser removido da raíz depois)
- Criar um release conforme é [explicado aqui](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository) postando o zip que você gerou. O release é a entrega de uma versão do Software. Sugiro usar a tag "v1.0.0"
- Obter o link desse release criado conforme [explicado aqui](https://docs.github.com/en/repositories/releasing-projects-on-github/linking-to-releases) e atualizar no README.md

**Comment by olvriz** [comment]
Muito obrigado pelo feedback e a sua sugestão Marcelo! Significa muito! 🎉

Acabei de realizar todos os ajustes! Qualquer outra ideia ou sugestão, por favor, pode me mandar!
